### ISSUE TITLE
[Outbreak] Some outbreaks being ignored by being too low in Spawner ID

### ISSUE THREAD

**Issue by RichardPaulAstley** [Lincoln-LM/PLA-Live-Map#2]
So if you remember well, I reported a few weeks ago where the outbreak was not searched because of the way the map was searching for the outbreak (searching from the last inactive spawner id to the last active spawner id)

You changed to scan more IDs but seems the issue isn't gone.

People had issues with Petill on the Crismon Mirelands

Guess reducing even more would be an idea ?

**Comment by lincoln-lm** [comment]
should be fixed as of [a9e93d0](https://github.com/Lincoln-LM/PLA-Live-Map/commit/a9e93d095b477b5aabbb9a9371e8a41f7565a79a)
